

const CLIENT_BASE = [
    {
        client_id: 0,
        client_fio: 'Ф.И.О',
        client_birth_date: 'Дата рождения',
        client_city: 'Город',
        client_phone: 'Номер телефона',
        client_social: 'Соц. сети',
        client_description: 'Комментарий',
        client_status: 'Статус клиента',
    },
    {
        client_id: 1,
        client_fio: 'Акакий Акакиев',
        client_birth_date: '11.12.1999',
        client_city: 'Екатеринбург',
        client_phone: '+79223874545',
        client_social: 'ВК',
        client_description: 'Не еблан, какает в лоток, не ест спущенку',
        client_status: '1',
    },
    {
        client_id: 2,
        client_fio: 'Ефросинья Акакиева',
        client_birth_date: '21.05.1993',
        client_city: 'Москва',
        client_phone: '+79223665454',
        client_social: 'ВК',
        client_description: 'Не дура, не какает, спит во сне',
        client_status: '1',
    },
    {
        client_id: 3,
        client_fio: 'Муфаса Умир',
        client_birth_date: '04.06.1995',
        client_city: 'Санкт-Петербург',
        client_phone: '+79193454486',
        client_social: 'ВК',
        client_description: 'Отец, удобрение, надо подкачаться',
        client_status: '2',
    },
    {
        client_id: 4,
        client_fio: 'Шрам Убица',
        client_birth_date: '11.06.1996',
        client_city: 'Санкт-Петербург',
        client_phone: '+79193454487',
        client_social: 'ВК',
        client_description: 'Обманщек, братоубица, корм для гиен',
        client_status: '1',
    },
    {
        client_id: 5,
        client_fio: 'Лень Придумывать',
        client_birth_date: '22.02.2009',
        client_city: 'Екатеринбург',
        client_phone: '+79224445565',
        client_social: 'ВК',
        client_description: 'Разрушительница жизней и семей, часто вместе со Срачем',
        client_status: '1',
    },
    {
        client_id: 6,
        client_fio: 'Срачь Воняющий',
        client_birth_date: '17.07.2001',
        client_city: 'Екатеринбург',
        client_phone: '+79223886756',
        client_social: 'ВК',
        client_description: 'Не воняет, а пахнет, не Срачь, а творческий беспорядок',
        client_status: '2',
    },
    {
        client_id: 1,
        client_fio: 'Акакий Акакиев',
        client_birth_date: '11.12.1999',
        client_city: 'Екатеринбург',
        client_phone: '+79223874545',
        client_social: 'ВК',
        client_description: 'Не еблан, какает в лоток, не ест спущенку',
        client_status: '1',
    },
    {
        client_id: 2,
        client_fio: 'Ефросинья Акакиева',
        client_birth_date: '21.05.1993',
        client_city: 'Москва',
        client_phone: '+79223665454',
        client_social: 'ВК',
        client_description: 'Не дура, не какает, спит во сне',
        client_status: '1',
    },
    {
        client_id: 3,
        client_fio: 'Муфаса Умир',
        client_birth_date: '04.06.1995',
        client_city: 'Санкт-Петербург',
        client_phone: '+79193454486',
        client_social: 'ВК',
        client_description: 'Отец, удобрение, надо подкачаться',
        client_status: '2',
    },
    {
        client_id: 4,
        client_fio: 'Шрам Убица',
        client_birth_date: '11.06.1996',
        client_city: 'Санкт-Петербург',
        client_phone: '+79193454487',
        client_social: 'ВК',
        client_description: 'Обманщек, братоубица, корм для гиен',
        client_status: '1',
    },
    {
        client_id: 5,
        client_fio: 'Лень Придумывать',
        client_birth_date: '22.02.2009',
        client_city: 'Екатеринбург',
        client_phone: '+79224445565',
        client_social: 'ВК',
        client_description: 'Разрушительница жизней и семей, часто вместе со Срачем',
        client_status: '1',
    },
    {
        client_id: 6,
        client_fio: 'Срачь Воняющий',
        client_birth_date: '17.07.2001',
        client_city: 'Екатеринбург',
        client_phone: '+79223886756',
        client_social: 'ВК',
        client_description: 'Не воняет, а пахнет, не Срачь, а творческий беспорядок',
        client_status: '2',
    },
    {
        client_id: 1,
        client_fio: 'Акакий Акакиев',
        client_birth_date: '11.12.1999',
        client_city: 'Екатеринбург',
        client_phone: '+79223874545',
        client_social: 'ВК',
        client_description: 'Не еблан, какает в лоток, не ест спущенку',
        client_status: '1',
    },
    {
        client_id: 2,
        client_fio: 'Ефросинья Акакиева',
        client_birth_date: '21.05.1993',
        client_city: 'Москва',
        client_phone: '+79223665454',
        client_social: 'ВК',
        client_description: 'Не дура, не какает, спит во сне',
        client_status: '1',
    },
    {
        client_id: 3,
        client_fio: 'Муфаса Умир',
        client_birth_date: '04.06.1995',
        client_city: 'Санкт-Петербург',
        client_phone: '+79193454486',
        client_social: 'ВК',
        client_description: 'Отец, удобрение, надо подкачаться',
        client_status: '2',
    },
    {
        client_id: 4,
        client_fio: 'Шрам Убица',
        client_birth_date: '11.06.1996',
        client_city: 'Санкт-Петербург',
        client_phone: '+79193454487',
        client_social: 'ВК',
        client_description: 'Обманщек, братоубица, корм для гиен',
        client_status: '1',
    },
    {
        client_id: 5,
        client_fio: 'Лень Придумывать',
        client_birth_date: '22.02.2009',
        client_city: 'Екатеринбург',
        client_phone: '+79224445565',
        client_social: 'ВК',
        client_description: 'Разрушительница жизней и семей, часто вместе со Срачем',
        client_status: '1',
    },
    {
        client_id: 6,
        client_fio: 'Срачь Воняющий',
        client_birth_date: '17.07.2001',
        client_city: 'Екатеринбург',
        client_phone: '+79223886756',
        client_social: 'ВК',
        client_description: 'Не воняет, а пахнет, не Срачь, а творческий беспорядок',
        client_status: '2',
    },

]

export default CLIENT_BASE;